### PR TITLE
[bot] [main] Automated dependencies update

### PR DESCRIPTION
**Pull request by roboquat**
Looks like some of our dependencies got updated upstream!

This is an automated PR updating those dependencies.
Configuration of the workflow is located in `.github/workflows/dep-update.yaml`

### CODE REVIEW

**Comment by laushinka** [comment]
How do I know if my changes[[1](https://github.com/gitpod-io/gitpod/pull/7541)] are reflected in this update?

**Comment by ArthurSens** [comment]
> How do I know if my changes[[1](https://github.com/gitpod-io/gitpod/pull/7541)] are reflected in this update?

@laushinka I don't think it has because this PR is 5 days old, and your PR got merged just yesterday :) 

You can find if your changes got updated by checking the file changes, you should see the files you've added/changed/deleted here as well

**Comment by ArthurSens** [comment]
And I'm surprised we haven't merged this yet, looks like our automation is not assigning any reviewers for some reason?

cc @mads-hartmann

**Comment by laushinka** [comment]
> @laushinka I don't think it has because this PR is 5 days old, and your PR got merged just yesterday :)
> 
> You can find if your changes got updated by checking the file changes, you should see the files you've added/changed/deleted here as well

@ArthurSens Thanks! Do I need to trigger it somehow? Or the bot runs once a week?

**Comment by ArthurSens** [comment]
I does run once a week, but you can also trigger it manually [here ](https://github.com/gitpod-io/observability/actions/workflows/dep-update.yaml)if you want your changes in production now

**Comment by laushinka** [comment]
Thank you! No rush, just wanted to know :)

**Pull request merged**
