### PR TITLE
service monitor resources

### PR DESCRIPTION
**Pull request by liam-j-bennett**
## Description
Wrapper functions for generating all the components for prometheus metrics

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by ArthurSens — COMMENTED** [review]
What do you think about adding a new package called `utils`?

Feels kinda weird a component `servicemonitor-wrapper` 🤔

**Comment by liam-j-bennett** [comment]
> What do you think about adding a new package called `utils`?
> 
> Feels kinda weird a component `servicemonitor-wrapper` 🤔

I don't like the idea of this being a utils package. Each of these is effectively a component, but to reduce code, we are iterating over all the underlying components. We could just call this the `gitpod` component and then create separate components for werft, cert-manager (and anything that these service monitor components are used). Then some of that code might go into a utils pkg

**Comment by liam-j-bennett** [comment]
I disabled the Go e2e checks. Even after fixing the segfaults, it wasn't working. It's not from this PR and don't really want to solve it as part of this work

**Comment by ArthurSens** [comment]
> I disabled the Go e2e checks. Even after fixing the segfaults, it wasn't working. It's not from this PR and don't really want to solve it as part of this work

It is fine! We know they are not passing 🙂, they are not blocking the merge.

**Comment by ArthurSens** [comment]
Hey @liam-j-bennett, while you were away I took the liberty to get this PR to completion 🙂 

Some changes I've made:
* Re-enabled the e2e-tests, we don't need them to pass at the moment.
* Rebased and fixed all linting problems
* Fixed Networkpolicies' Kind from `ServiceMonitor` to `NetworkPolicy`

**Pull request merged**
